services:
  migrate:
    image: pgweb-migrator:latest
    container_name: pgweb_migrator
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGWEB_DATABASE_URL: "INSERT_YOUR_DATABASE_URL_HERE"
    networks:
      - app

  frontend:
    image: pgweb-frontend
    container_name: pgwerb_frontend
    networks:
      - app
    ports:
      - "5173:80"

  api:
    image: pgweb-service:latest
    container_name: pgweb_api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - app

  db:
    image: postgres:16-alpine
    container_name: pgweb_postgres
    environment:
      POSTGRES_DB: pgweb
      POSTGRES_USER: pgweb
      POSTGRES_PASSWORD: pgweb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      app:
        aliases:
          - pgweb_postgres

volumes:
  pgdata:
    driver: local

networks:
  app:
    driver: bridge
